version: '3.8'

services:
  reader:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ORACLE_CSV_PATH=/logs/output.csv
      - CKN_LOG_FILE=/logs/ckn.log
      - CKN_KAFKA_BROKER=<public_ip>:9092
      - CKN_KAFKA_TOPIC=oracle-events
      - CAMERA_TRAPS_DEVICE_ID=device_1

    volumes:
      - /Users/swithana/git/d2i/icicle-ckn/oracle_ckn_daemon:/logs:r