version: '3.8'

services:
  ckn-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CKN_KAFKA_BROKER=127.0.0.1:9092
      - CKN_KAFKA_TOPIC=oracle-events
      - CKN_LOG_FILE=ckn_example.log

    networks:
      - ckn-network

networks:
  ckn-network:
    driver: bridge
