version: '3.8'

services:
  ckn-daemon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: example-plugin
    environment:
      - CKN_KAFKA_BROKER=broker:29092
      - CKN_KAFKA_TOPIC=oracle-events
    volumes:
      - ./:/app
    networks:
      - ckn-network

networks:
  ckn-network:
    external: True