version: '3.8'

services:
  neo4j:
    image: neo4j:5.21.0-community
    container_name: neo4j_server
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/PWD_HERE
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "neo4j status"]
      interval: 10s
      timeout: 5s
      retries: 5

  ckn-dashboard:
    image: iud2i/ckn-analytics-dashboard:latest
    depends_on:
      neo4j:
        condition: service_healthy
    ports:
      - "8502:8502"

    environment:
      - CKN_KG_URI=bolt://localhost:7687
      - CKN_KG_USER=neo4j
      - CKN_KG_PWD=pwd

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins: