name: CKN-CI

on: [push]

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build CKN
        run: |
          docker network create ckn-network || true
          docker compose -f docker-compose.yml up -d --build
      
      - name: Build Plugin
        run: |
          docker compose -f plugins/oracle_ckn_daemon/docker-compose.yml up -d --build
    
  run:
    runs-on: ubuntu-latest
    needs: start
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Produce Plugin Events
        run: |
          docker exec oracle-daemon touch /oracle_logs/image_mapping_final.json

  test:
    runs-on: ubuntu-latest
    needs: [start, run]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test Plugin
        run: |
          pip install -r plugins/oracle_ckn_daemon/tests/requirements.txt
          python -m unittest discover -s plugins/oracle_ckn_daemon/tests -p "*.py"

  stop:
    runs-on: ubuntu-latest
    needs: start
    steps:
    - name: Stop and Remove CKN Docker Network
      if: always()
      run: |
        docker compose down
        docker rm oracle-daemon || true
        docker network rm ckn-network || true
